from pathlib import Path
exec(Path(__file__).with_name('common.py').read_text())
cmd=['agent-browser','--session','coherent-immersive-advanced'];call('--init-script',str(Path(__file__).with_name('capture-errors.js')),'open',root.joinpath('index-3d.html').as_uri());call('set','viewport','1440','1050','1')
rows={}
load(out/'legal-early-automation-before.json');focus('overview');scroll();call('screenshot',str(out/'early-automation-before.png'));rows['earlyBefore']=info();call('click','[data-upgrade=automation]');wait();scroll();call('screenshot',str(out/'early-automation-after.png'));rows['earlyAfter']=info();assert rows['earlyBefore']['diagnostics']['chapter']==rows['earlyAfter']['diagnostics']['chapter']==3;assert rows['earlyAfter']['diagnostics']['model']['analysisStations']==1
load(old/'frontier-ready.json');
if not evaluate('Coherent3D.diagnostics.followExperiment'):call('click','#three-follow')
call('click','#three-pause');call('click','#three-expand');wait();call('click','#run-experiment');rows['fullscreenWorkloadNavigation']=evaluate("(()=>{const r=document.getElementById('workload-section').getBoundingClientRect();return {target:document.fullscreenElement?.id,containsWorkloads:document.fullscreenElement?.contains(document.getElementById('workload-section')),top:r.top,viewport:innerHeight,visible:r.top>=-1&&r.top<innerHeight}})()");assert rows['fullscreenWorkloadNavigation']['containsWorkloads'] and rows['fullscreenWorkloadNavigation']['visible'];call('click','[data-run-workload=dynamics]');wait(950);rows['fullscreenActive']=info();call('screenshot',str(out/'fullscreen-active.png'))
for i in range(8):
 wait(10000)
 ended=evaluate('!document.getElementById("ending-view").hidden');print('Fullscreen workload check '+str(i+1)+' ended='+str(ended),flush=True)
 if ended:break
assert ended,'native schedule failed to reach ending'
rows['fullscreenEnding']=evaluate("(()=>({target:document.fullscreenElement?.id,endingVisible:!document.getElementById('ending-view').hidden,containsEnding:document.fullscreenElement?.contains(document.getElementById('ending-view')),diagnostics:Coherent3D.diagnostics}))()");assert rows['fullscreenEnding']['target']=='main' and rows['fullscreenEnding']['containsEnding'];call('screenshot',str(out/'fullscreen-ending.png'));call('press','Escape')
load(out/'legal-native-before.json');call('click','[data-dialog=settings-dialog]');call('click','#theme-toggle');call('click','[data-close=settings-dialog]');focus('cryostat');scroll();rows['lightTheme']=info();call('screenshot',str(out/'light-cryostat.png'))
# Actual native drag respects manual inspection and changes no paused save.
evaluate("window.coherentDragSave=localStorage.getItem('coherent.v2')");follow=evaluate('Coherent3D.diagnostics.followExperiment');
if not follow:call('click','#three-follow')
b=evaluate("(()=>{const r=document.getElementById('three-canvas').getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()");call('mouse','move',str(b['x']),str(b['y']));call('mouse','down','left');call('mouse','move',str(b['x']+85),str(b['y']+15));call('mouse','up','left');wait();rows['orbitDrag']=evaluate("({follow:Coherent3D.diagnostics.followExperiment,unchanged:coherentDragSave===localStorage.getItem('coherent.v2')})");assert not rows['orbitDrag']['follow'] and rows['orbitDrag']['unchanged']
# Actual context loss must preserve the paused game, stop GPU work and restore 2D.
evaluate("window.coherentBeforeLoss=localStorage.getItem('coherent.v2');window.coherentLose=document.getElementById('three-canvas').getContext('webgl2').getExtension('WEBGL_lose_context');coherentLose.loseContext()");wait(350);rows['contextLoss']=info();rows['contextLoss']['unchanged']=evaluate("coherentBeforeLoss===localStorage.getItem('coherent.v2')");rows['contextLoss']['machine']=evaluate('getComputedStyle(document.getElementById("machine")).display');assert not rows['contextLoss']['diagnostics']['available'] and rows['contextLoss']['unchanged'] and rows['contextLoss']['machine']=='block';call('screenshot',str(out/'context-loss-2d.png'))
evaluate('coherentLose.restoreContext()');wait(400);rows['contextRestorationKeepsFallback']=not info()['diagnostics']['available'];assert rows['contextRestorationKeepsFallback']
call('click','#pause-toggle');wait(800);call('click','#pause-toggle');call('click','[data-dialog=settings-dialog]');call('download','#settings-dialog [data-action=export]',str(out/'context-loss-export.json'));call('click','[data-close=settings-dialog]');call('reload');wait();rows['reloadRecovery']=info();assert rows['reloadRecovery']['diagnostics']['available']
load(old/'schedule-unqualified.json');focus('planning');scroll();rows['unqualifiedSchedule']=info();assert 'lower bound' in rows['unqualifiedSchedule']['description'];call('screenshot',str(out/'schedule-unqualified.png'))
call('set','viewport','375','1000','3');load(out/'legal-native-before.json');call('click','#three-pause');wait();rows['mobileMotion']=sample(1000);assert 1<=rows['mobileMotion']['delta']<=21 and rows['mobileMotion']['after']['cadence']==20;call('click','#three-pause');call('focus','[data-camera=reset]');call('press','Enter');wait();rows['mobileKeyboardLastStation']=evaluate("({camera:Coherent3D.diagnostics.camera,focus:document.activeElement.textContent,scroll:document.getElementById('three-stations').scrollLeft})");rows['errors']=evaluate('coherentQAErrors');assert not rows['errors'];(out/'advanced.json').write_text(json.dumps(rows,indent=2)+'\n');call('close');print('Advanced native fullscreen ending, context loss, orbit and mobile checks complete',flush=True)
