from pathlib import Path
exec(Path(__file__).with_name('common.py').read_text())
cmd=['agent-browser','--session','coherent-immersive-visibility'];call('--init-script',str(Path(__file__).with_name('capture-errors.js')),'open',root.joinpath('index-3d.html').as_uri());call('set','viewport','1440','1050','1');load(out/'legal-native-before.json');focus('overview');scroll();call('click','#three-pause');wait(150)
rows={};rows['before']=info();call('click','[data-upgrade=hardware]');wait(1000)
rows['purchaseViewport']=evaluate("(()=>{const c=document.getElementById('three-canvas').getBoundingClientRect(),t=document.getElementById('three-expansion').getBoundingClientRect();return {canvas:{top:c.top,bottom:c.bottom},cue:{top:t.top,bottom:t.bottom,text:document.getElementById('three-expansion-message').textContent,hidden:document.getElementById('three-expansion').hidden},viewport:innerHeight,diagnostics:Coherent3D.diagnostics}})()");assert not rows['purchaseViewport']['cue']['hidden'];assert rows['purchaseViewport']['cue']['top']>=0 and rows['purchaseViewport']['cue']['bottom']<=1050;assert not rows['purchaseViewport']['diagnostics']['inViewport'];rows['offscreen']=sample(700);assert rows['offscreen']['delta']==0;call('screenshot',str(out/'ordinary-purchase-cue.png'))
call('click','#three-inspect-expansion');wait(100);rows['returnedReveal']=evaluate("(()=>({diagnostics:Coherent3D.diagnostics,opacity:getComputedStyle(document.getElementById('three-canvas')).opacity,animations:document.getElementById('three-canvas').getAnimations().map(a=>({name:a.animationName,time:a.currentTime}))}))()");assert rows['returnedReveal']['diagnostics']['inViewport'] and rows['returnedReveal']['diagnostics']['model']['modulePackages']==4;assert any(a['name']=='three-assembly' and 0<=a['time']<650 for a in rows['returnedReveal']['animations']);call('screenshot',str(out/'returned-expansion-reveal.png'));wait(750);scroll();call('screenshot',str(out/'returned-expansion.png'));rows['returnedActive']=sample(700);assert rows['returnedActive']['delta']>0
# A paused mobile purchase cue does not obscure the fixed native experiment action; keyboard returns to the lab.
call('set','viewport','375','1000','3');load(out/'legal-native-before.json');call('click','[data-upgrade=automation]');wait(150);rows['mobileCue']=evaluate("(()=>{const c=document.getElementById('three-expansion').getBoundingClientRect(),a=document.getElementById('run-experiment').getBoundingClientRect();return {cue:{top:c.top,bottom:c.bottom},action:{top:a.top,bottom:a.bottom},hidden:document.getElementById('three-expansion').hidden,overflow:document.documentElement.scrollWidth>innerWidth}})()");assert not rows['mobileCue']['hidden'] and rows['mobileCue']['cue']['bottom']<rows['mobileCue']['action']['top'] and not rows['mobileCue']['overflow'];call('screenshot',str(out/'mobile-purchase-cue.png'));evaluate("window.coherentCueSave=localStorage.getItem('coherent.v2')");call('focus','#three-inspect-expansion');call('press','Enter');wait();rows['keyboardCueReturn']=evaluate("({diagnostics:Coherent3D.diagnostics,unchanged:coherentCueSave===localStorage.getItem('coherent.v2'),focus:document.activeElement.textContent})");assert rows['keyboardCueReturn']['unchanged'] and rows['keyboardCueReturn']['diagnostics']['model']['analysisStations']==4
# Follow mode brings a reduced-motion experiment into view with an instant static camera.
call('set','viewport','1440','1050','1');load(out/'unstarted.json');
if not evaluate('Coherent3D.diagnostics.followExperiment'):call('click','#three-follow')
call('set','media','dark','reduced-motion');call('click','#run-experiment');wait();rows['reducedFollow']=info();rows['reducedFollowFrames']=sample(650);assert rows['reducedFollow']['diagnostics']['camera']=='cryostat' and rows['reducedFollow']['diagnostics']['inViewport'] and rows['reducedFollowFrames']['delta']==0;scroll();call('screenshot',str(out/'reduced-follow.png'));call('click','#three-pause');call('set','media','dark');rows['errors']=evaluate('coherentQAErrors');assert not rows['errors'];(out/'visibility.json').write_text(json.dumps(rows,indent=2)+'\n');call('close');print('Visible cue, deferred reveal, offscreen stop, keyboard/mobile cue and reduced follow pass',flush=True)
